/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'

const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRoute
  '/listings/$slug': typeof ListingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRoute
  '/listings/$slug': typeof ListingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communities': typeof CommunitiesRoute
  '/contact': typeof ContactRoute
  '/listings': typeof ListingsRouteWithChildren
  '/sold': typeof SoldRoute
  '/listings/$slug': typeof ListingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/communities'
    | '/contact'
    | '/listings'
    | '/sold'
    | '/listings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/communities'
    | '/contact'
    | '/listings'
    | '/sold'
    | '/listings/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/communities'
    | '/contact'
    | '/listings'
    | '/sold'
    | '/listings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunitiesRoute: typeof CommunitiesRoute
  ContactRoute: typeof ContactRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  SoldRoute: typeof SoldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
  }
}

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunitiesRoute: CommunitiesRoute,
  ContactRoute: ContactRoute,
  ListingsRoute: ListingsRouteWithChildren,
  SoldRoute: SoldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
